### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by masammut** [chrismarch/SoftBodySimulation#1]
Hi, what's the license for this repository please? MIT?

**Comment by chrismarch** [comment]
Hello,
Sorry for the late reply. I didn't anticipate much interest from others in this code sample, so I neglected to choose a license. I may reconsider, if there is still interest. Here is the default license behavior for github repos with no explicit license: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by chrismarch** [comment]
I've assigned the GPL v3 license
